USE [STOCK_INFO]
GO

/****** Object:  Index [IDX_DAILY_KOSP]    Script Date: 2019-01-20 오후 11:46:48 ******/
CREATE NONCLUSTERED INDEX [IDX_DAILY_KOSP] ON [dbo].[DAILY_KOSP]
(
	[CCODE] ASC,
	[DDATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


USE [STOCK_INFO]
GO

/****** Object:  Index [idx_stock_min]    Script Date: 2019-01-20 오후 11:47:06 ******/
CREATE NONCLUSTERED INDEX [idx_stock_min] ON [dbo].[STOCK_MIN]
(
	[CCODE] ASC,
	[DDATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


